package com.pakt.adapty.controller;

import javafx.scene.input.MouseButton;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;

public class SmileysView {

    public Text _00;
    public Text _10;
    public Text _20;
    public Text _30;
    public Text _40;
    public Text _50;
    public Text _60;
    public Text _70;
    public Text _01;
    public Text _11;
    public Text _21;
    public Text _31;
    public Text _41;
    public Text _51;
    public Text _61;
    public Text _71;
    public Text _02;
    public Text _12;
    public Text _22;
    public Text _32;
    public Text _42;
    public Text _52;
    public Text _62;
    public Text _72;
    public Text _03;
    public Text _13;
    public Text _23;
    public Text _33;
    public Text _43;
    public Text _53;
    public Text _63;
    public Text _73;
    public Text _04;
    public Text _14;
    public Text _24;
    public Text _34;
    public Text _44;
    public Text _54;
    public Text _64;
    public Text _74;
    public Text _05;
    public Text _15;
    public Text _25;
    public Text _35;
    public Text _45;
    public Text _55;
    public Text _65;
    public Text _75;
    public Text _06;
    public Text _16;
    public Text _26;
    public Text _36;
    public Text _46;
    public Text _56;
    public Text _66;
    public Text _76;
    public Text _07;
    public Text _17;
    public Text _27;
    public Text _37;
    public Text _47;
    public Text _57;
    public Text _67;
    public Text _77;
    public Text _08;
    public Text _18;
    public Text _28;
    public Text _38;
    public Text _48;
    public Text _58;
    public Text _68;
    public Text _78;
    public Text _09;
    public Text _19;
    public Text _29;
    public Text _39;
    public Text _49;
    public Text _59;
    public Text _69;
    public Text _79;
    public Text _010;
    public Text _110;
    public Text _210;
    public Text _310;
    public Text _410;
    public Text _510;
    public Text _610;
    public Text _710;
    public Text _011;
    public Text _111;
    public Text _211;
    public Text _311;
    public Text _411;
    public Text _511;
    public Text _611;
    public Text _711;
    public Text _012;
    public Text _112;
    public Text _212;
    public Text _312;
    public Text _412;
    public Text _512;
    public Text _612;
    public Text _712;
    public Text _013;
    public Text _113;
    public Text _213;
    public Text _313;
    public Text _413;
    public Text _513;
    public Text _613;
    public Text _713;
    public Text _014;
    public Text _114;

    public void initialize() {
        insertSmiley(_00);
        insertSmiley(_10);
        insertSmiley(_20);
        insertSmiley(_30);
        insertSmiley(_40);
        insertSmiley(_50);
        insertSmiley(_60);
        insertSmiley(_70);
        insertSmiley(_01);
        insertSmiley(_11);
        insertSmiley(_21);
        insertSmiley(_31);
        insertSmiley(_41);
        insertSmiley(_51);
        insertSmiley(_61);
        insertSmiley(_71);
        insertSmiley(_02);
        insertSmiley(_12);
        insertSmiley(_22);
        insertSmiley(_32);
        insertSmiley(_42);
        insertSmiley(_52);
        insertSmiley(_62);
        insertSmiley(_72);
        insertSmiley(_03);
        insertSmiley(_13);
        insertSmiley(_23);
        insertSmiley(_33);
        insertSmiley(_43);
        insertSmiley(_53);
        insertSmiley(_63);
        insertSmiley(_73);
        insertSmiley(_04);
        insertSmiley(_14);
        insertSmiley(_24);
        insertSmiley(_34);
        insertSmiley(_44);
        insertSmiley(_54);
        insertSmiley(_64);
        insertSmiley(_74);
        insertSmiley(_05);
        insertSmiley(_15);
        insertSmiley(_25);
        insertSmiley(_35);
        insertSmiley(_45);
        insertSmiley(_55);
        insertSmiley(_65);
        insertSmiley(_75);
        insertSmiley(_06);
        insertSmiley(_16);
        insertSmiley(_26);
        insertSmiley(_36);
        insertSmiley(_46);
        insertSmiley(_56);
        insertSmiley(_66);
        insertSmiley(_76);
        insertSmiley(_07);
        insertSmiley(_17);
        insertSmiley(_27);
        insertSmiley(_37);
        insertSmiley(_47);
        insertSmiley(_57);
        insertSmiley(_67);
        insertSmiley(_77);
        insertSmiley(_08);
        insertSmiley(_18);
        insertSmiley(_28);
        insertSmiley(_38);
        insertSmiley(_48);
        insertSmiley(_58);
        insertSmiley(_68);
        insertSmiley(_78);
        insertSmiley(_09);
        insertSmiley(_19);
        insertSmiley(_29);
        insertSmiley(_39);
        insertSmiley(_49);
        insertSmiley(_59);
        insertSmiley(_69);
        insertSmiley(_79);
        insertSmiley(_010);
        insertSmiley(_110);
        insertSmiley(_210);
        insertSmiley(_310);
        insertSmiley(_410);
        insertSmiley(_510);
        insertSmiley(_610);
        insertSmiley(_710);
        insertSmiley(_011);
        insertSmiley(_111);
        insertSmiley(_211);
        insertSmiley(_311);
        insertSmiley(_411);
        insertSmiley(_511);
        insertSmiley(_611);
        insertSmiley(_711);
        insertSmiley(_012);
        insertSmiley(_112);
        insertSmiley(_212);
        insertSmiley(_312);
        insertSmiley(_412);
        insertSmiley(_512);
        insertSmiley(_612);
        insertSmiley(_712);
        insertSmiley(_013);
        insertSmiley(_113);
        insertSmiley(_213);
        insertSmiley(_313);
        insertSmiley(_413);
        insertSmiley(_513);
        insertSmiley(_613);
        insertSmiley(_713);
        insertSmiley(_014);
        insertSmiley(_114);
    }

    private void insertSmiley(Text smiley) {
        smiley.setFill(Color.valueOf("#22252b"));
        smiley.setOnMousePressed(event -> {
            if (event.getButton() == MouseButton.PRIMARY) {
                var currentTextArea = MainView.currentTab.getTextArea();
                var caretPos =  currentTextArea.getCaretPosition();
                currentTextArea.insertText(caretPos, smiley.getText());
            };
        });
    }
}
